name: Skaffold
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml
      - action.yml
jobs:
  pipiline:
    name: Skaffold Pipiline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest

      - name: Setup Helm
        uses: hiberbee/github-action-helm@latest
        with:
          repository-config: test/repositories.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.SKAFFOLD_DEFAULT_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
          default-repo: ${{ secrets.SKAFFOLD_DEFAULT_REPO }}

      - name: Get Helm releases
        run: helm list
