name: Skaffold
on:
  push:
    paths:
      - lib/**
      - .github/workflows/skaffold.yml
jobs:
  pipiline:
    name: Skaffold Pipiline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest

      - name: Setup Helm
        uses: hiberbee/github-action-helm@latest

      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
          default-repo: harbor.k8s.hiberbee.net/library

      - name: Get Helm releases
        run: helm list
